### ISSUE TITLE
KeyError of 'run_with_numpy'

### ISSUE THREAD

**Issue by Wakaura** [mdrft/Blueqat#21]
I installed and executed the program of simple quantum circuit. But, keyerror occurs in circuit.py because of 'run_with_numpy'.

Executed program here.
# -*- coding: utf-8 -*-
"""
Created on Tue Oct  2 18:54:54 2018

@author: ****
"""

from blueqat import Circuit
import numpy as np
for i in range(100):
    c = Circuit().x[3].x[3].x[0].rx(-np.pi/2)[0].ry(np.pi/2)[1]
    c = c.cnot[1, 0].rz(np.pi/2)[0].cnot[1, 0].rx(np.pi/2)[0].ry(-np.pi/2)[1].m[:]
    c.run()
    print(c.last_result()) # => (1, 1)

Result here.
runfile('C:/Users/s1430/blueqatH2vqencitest1.py', wdir='C:/Users/s1430')
Reloaded modules: blueqat, blueqat.circuit, blueqat.gate, blueqat.backends.numpy_backend, blueqat.backends.backendbase, blueqat.backends.qasm_output_backend, blueqat.backends.mqc_backend, blueqat.pauli, blueqat.utils, blueqat.vqe
Traceback (most recent call last):

  File "<ipython-input-15-c1f1deb6d266>", line 1, in <module>
    runfile('C:/Users/s1430/blueqatH2vqencitest1.py', wdir='C:/Users/s1430')

  File "C:\Users\s1430\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\s1430\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/s1430/blueqatH2vqencitest1.py", line 14, in <module>
    print(c.last_result()) # => (1, 1)

  File "c:\users\s1430\downloads\blueqat-master_new\blueqat-master\blueqat\circuit.py", line 139, in last_result
    return self._backends["run_with_numpy"].run_history[-1]

KeyError: 'run_with_numpy'

**Comment by gyu-don** [comment]
`last_result` is now not recommended.
Plz use `c.run(shots=1)`

**Comment by Wakaura** [comment]
So, how I see the result?

**Comment by gyu-don** [comment]
`Circuit().x[1].m[:].run(shots=1)` returns `Counter({'01': 1})`
