### ISSUE TITLE
Sympy Unitary Matrix Backend

### ISSUE THREAD

**Issue by gyu-don** [mdrft/Blueqat#24]
The backend which returns sympy's unitary matrix.

```py
Circuit().h[0].run(backend="sympy_unitary")
# => Matrix([
# => [sqrt(2)/2,  sqrt(2)/2],
# => [sqrt(2)/2, -sqrt(2)/2]])
```

Requrements:

- Use Sympy's Matrix.
- When sympy is not installed, this backend is unavailable however Blueqat and other backends are available.
- At least, following gates shall be implemented: X/Y/Z/U3/RX/RY/RZ/CX/CZ
- Unit test

Optional Requirements:

- Sampling (`run(shots=...)`)
- Pretty output for Jupyter Notebook

**Comment by gyu-don** [comment]
- H gate also shall be implemented.

Measuring until circuit ends is very difficult. (split to 2 matrix for each measurement)
So, measurement is not required.

**Comment by ymurata** [comment]
https://github.com/mdrft/Blueqat/pull/36
