### ISSUE TITLE
Local install error

### ISSUE THREAD

**Issue by Wakaura** [mdrft/Blueqat#9]
Local instllation isn't be successful. setup.py emerges some errors.

(base) C:\Users\s1430\Downloads\Blueqat-master_test\Blueqat-master>pip install -e .
Obtaining file:///C:/Users/s1430/Downloads/Blueqat-master_test/Blueqat-master
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\s1430\Downloads\Blueqat-master_test\Blueqat-master\setup.py", line 4, in <module>
        long_description = f.read()
    UnicodeDecodeError: 'cp932' codec can't decode byte 0x84 in position 1477: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\s1430\Downloads\Blueqat-master_test\Blueqat-master\

I want to modify blueqat locally for emergent business. I wish this problem will be solved soon.

**Comment by gyu-don** [comment]
Fixed. Please check again and if OK, close this issue.
